baseURL = 'https://answer42.xyz/'
languageCode = 'en-us'
title = 'Answer42.xyz: Blog & Coffee'
theme = 'congo'

[[menu.main]]
name = "Tags"
url = "/tags/"
weight = 10

[[menu.main]]
name = "Projects"
url = "/projects/"
weight = 20

[[menu.main]]
name = "Posts"
url = "/posts/"
weight = 30

# [[menu.main]]
# name = "Reviews"
# url = "/reviews/"
# weight = 40
